//
// Generated by EzInkscape
// Inkscape: drawing.svg
// Language: objective-c
// Date: 18/08/2014 20:55:19
//

// Menu
const static float kMenu_X = -0.08035364;
const static float kMenu_Y = 0.7706325;

const NSString *kBackgroundMenu = @"BackgroundMenu.png";
const static float kBackgroundMenu_X = -0.08035364;
const static float kBackgroundMenu_Y = 0.7706325;
const static float kBackgroundMenu_W = 320;
const static float kBackgroundMenu_H = 480;

const NSString *kButtonStart = @"ButtonStart.png";
const static float kButtonStart_X = 79.919649;
const static float kButtonStart_Y = 160.77059;
const static float kButtonStart_W = 160;
const static float kButtonStart_H = 160;

// Logo
const static float kLogo_X = 65.716522;
const static float kLogo_Y = 55.377342;

const NSString *kLogo = @"Logo.png";
const static float kLogo_X = 65.716522;
const static float kLogo_Y = 55.377342;
const static float kLogo_W = 188.40625;
const static float kLogo_H = 29.984375;

// Objects
const static float kObjects_X = 79.919647;
const static float kObjects_Y = 359.77539;

const NSString *kObjectA = @"ObjectA.png";
const static float kObjectA_X = 79.919647;
const static float kObjectA_Y = 359.77539;
const static float kObjectA_W = 40;
const static float kObjectA_H = 40;

const NSString *kObjectB = @"ObjectB.png";
const static float kObjectB_X = 119.91965;
const static float kObjectB_Y = 359.77539;
const static float kObjectB_W = 40;
const static float kObjectB_H = 40;

const NSString *kObjectC = @"ObjectC.png";
const static float kObjectC_X = 159.91965;
const static float kObjectC_Y = 359.77539;
const static float kObjectC_W = 40;
const static float kObjectC_H = 40;

const NSString *kObjectD = @"ObjectD.png";
const static float kObjectD_X = 199.91965;
const static float kObjectD_Y = 359.77539;
const static float kObjectD_W = 40;
const static float kObjectD_H = 40;

